# Generated by Django 6.0.1 on 2026-02-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0003_userprofilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepic',
            name='photo',
            field=models.ImageField(default='users_profile_pics/default.png', upload_to='users_profile_pics'),
        ),
    ]
