# Generated by Django 6.0.1 on 2026-02-18 19:38

import django.db.models.deletion
import docs_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0005_alter_userprofilepic_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MdDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('doc', models.FileField(upload_to=docs_manager.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
