# Generated by Django 6.0.1 on 2026-02-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0006_mddocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mddocs',
            name='ref',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
