# Generated by Django 6.0.1 on 2026-02-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0007_mddocs_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='mddocs',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mddocs',
            name='ref',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
