# Generated by Django 6.0.1 on 2026-02-19 09:59

import django.core.validators
import django.db.models.deletion
import docs_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0008_mddocs_is_public_alter_mddocs_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='MdDocsAttachedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to=docs_manager.models.attached_images_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), docs_manager.models.validate_images_size])),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_images', to='docs_manager.mddocs')),
            ],
        ),
    ]
