# Generated by Django 6.0.1 on 2026-02-19 10:54

import django.core.validators
import django.db.models.deletion
import docs_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0009_mddocsattachedimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mddocsattachedimages',
            name='photo',
            field=models.ImageField(upload_to=docs_manager.models.attached_images_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), docs_manager.models.validate_images_size]),
        ),
        migrations.CreateModel(
            name='MdDocsAttachedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('audio', models.FileField(upload_to=docs_manager.models.attached_audio_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'acc']), docs_manager.models.validate_audio_size])),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_audio', to='docs_manager.mddocs')),
            ],
        ),
        migrations.CreateModel(
            name='MdDocsAttachedDivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=docs_manager.models.attached_divers_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ggb']), docs_manager.models.validate_divers_size])),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_divers', to='docs_manager.mddocs')),
            ],
        ),
        migrations.CreateModel(
            name='MdDocsAttachedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(upload_to=docs_manager.models.attached_videos_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'mpg']), docs_manager.models.validate_videos_size])),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_videos', to='docs_manager.mddocs')),
            ],
        ),
    ]
