# Generated by Django 6.0.1 on 2026-02-19 10:57

import django.core.validators
import docs_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0010_alter_mddocsattachedimages_photo_mddocsattachedaudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mddocsattachedaudio',
            name='audio',
            field=models.FileField(upload_to=docs_manager.models.attached_audio_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'acc', 'wav']), docs_manager.models.validate_audio_size]),
        ),
    ]
