# Generated by Django 6.0.1 on 2026-02-19 11:04

import django.core.validators
import docs_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0011_alter_mddocsattachedaudio_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mddocsattacheddivers',
            name='file',
            field=models.FileField(upload_to=docs_manager.models.attached_divers_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ggb', 'zip']), docs_manager.models.validate_divers_size]),
        ),
    ]
