# Generated by Django 6.0.1 on 2026-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0012_alter_mddocsattacheddivers_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=50)),
                ('motif', models.TextField(default='n/a')),
            ],
        ),
    ]
