# Generated by Django 6.0.1 on 2026-03-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_manager', '0015_userinformations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinformations',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
