"""
Django settings for icartable_docs project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = f'{os.getenv("SECRET_KEY")}'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'docs_manager',
    'storages',
    'django_cleanup.apps.CleanupConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'icartable_docs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'icartable_docs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

STATICFILES_DIRS=[
    BASE_DIR / "static",
]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER=f'{os.getenv("EMAIL_HOST_USER")}'
EMAIL_HOST_PASSWORD=f'{os.getenv("EMAIL_HOST_PASSWORD")}'
DEFAULT_FROM_EMAIL=EMAIL_HOST_USER

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LOGIN_URL="/"



# --- 1. CONFIGURATION MINIO (MEDIA) ---
# Vos identifiants MinIO
AWS_ACCESS_KEY_ID = 'Malik'
# ATTENTION : MinIO exige 8 caractères minimum, assurez-vous d'avoir changé "123o"
AWS_SECRET_ACCESS_KEY = '1234@KeCo' 

# Le nom du bucket que vous devrez créer dans l'interface MinIO
AWS_STORAGE_BUCKET_NAME = 'media'

# L'URL de l'API MinIO (Le port par défaut est 9000, pas 9001 !)
# Si Django tourne en local (hors docker) :
AWS_S3_ENDPOINT_URL = 'http://127.0.0.1:9000'
# Si Django tourne DANS Docker sur le même réseau que MinIO :
# AWS_S3_ENDPOINT_URL = 'http://minio:9000' (remplacez 'minio' par le nom du service dans docker-compose)

AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False  # Si un fichier a le même nom, on le renomme au lieu d'écraser
AWS_S3_VERIFY = False  # Désactive la vérification SSL (car vous êtes en HTTP)
AWS_S3_USE_SSL = False

# --- 2. CONFIGURATION HYBRIDE (STORAGES) ---
STORAGES = {
    # "default" gère les uploads (FileField, ImageField) -> Vers MinIO
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    # "staticfiles" gère le CSS/JS -> Reste en Local
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# --- 3. URLs ---
AWS_S3_URL_PROTOCOL = 'http:'
# URL pour accéder aux médias (images uploadées)
# Cela doit correspondre à l'adresse de votre bucket
AWS_S3_CUSTOM_DOMAIN = f'127.0.0.1:9000/{AWS_STORAGE_BUCKET_NAME}'
MEDIA_URL = f'/{STORAGES["default"]["OPTIONS"]["location"]}/' if 'location' in STORAGES.get("default", {}).get("OPTIONS", {}) else '/'

# URL pour les fichiers statiques (local)
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # Votre dossier static à la racine
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')   # Dossier collecté